name: Builds

on:
  push:
    branches: ['**']

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    environment:
      name: 'Build'
    runs-on: namespace-profile-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: justryanw
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Build Client
        run: nix build